[package]
name = "fuzzr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
clap = "3.2"
rayon = "1.5"
regex = "1.5"